# Generated by Django 3.2.5 on 2021-07-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barman', '0002_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'درباره ما'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
        migrations.AlterField(
            model_name='about',
            name='section_one',
            field=models.CharField(max_length=200, verbose_name='توضیحات بخش اول'),
        ),
        migrations.AlterField(
            model_name='about',
            name='section_two',
            field=models.CharField(max_length=200, verbose_name='توضیحات بخش دوم'),
        ),
    ]
