# Generated by Django 3.2.5 on 2021-07-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barman', '0003_auto_20210712_1053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
