# Generated by Django 3.2.5 on 2021-07-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barman', '0005_ab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ab',
            name='name',
        ),
        migrations.AddField(
            model_name='ab',
            name='name_one',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان بخش اول'),
        ),
    ]
