# Generated by Django 3.2.5 on 2021-07-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barman', '0012_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام و نام خانوادگی')),
                ('email', models.CharField(max_length=200, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('description', models.TextField(blank=True, null=True, verbose_name='پیغام شما')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
