# Generated by Django 3.2.5 on 2021-07-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barman', '0013_auto_20210717_1708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
