# Generated by Django 3.2.5 on 2021-07-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barman', '0014_delete_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ab',
            options={'verbose_name': 'درباره ما', 'verbose_name_plural': 'درباره ما'},
        ),
        migrations.AlterModelOptions(
            name='cont',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'تماس با ما'},
        ),
        migrations.AlterModelOptions(
            name='data_form',
            options={'verbose_name': 'فرم دریافتی', 'verbose_name_plural': 'فرم دریافتی'},
        ),
    ]
