# Generated by Django 3.2.5 on 2021-07-07 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام زیر دسته')),
                ('description', models.TextField(verbose_name='توضیحات زیر دسته')),
                ('khadamat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barman.khadamat', verbose_name='خدمات')),
            ],
            options={
                'verbose_name': 'زیر دسته',
                'verbose_name_plural': 'زیر دسته',
            },
        ),
    ]
