# Generated by Django 3.2.5 on 2021-07-07 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barman', '0002_subset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nemune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نمونه')),
                ('khadamat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barman.khadamat', verbose_name='خدمات')),
                ('subset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barman.subset', verbose_name='زیر ذسته')),
            ],
            options={
                'verbose_name': 'نمونه',
                'verbose_name_plural': 'نمونه',
            },
        ),
    ]
