# Generated by Django 3.2.5 on 2021-07-07 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barman', '0003_nemune'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkillSubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory', models.CharField(max_length=100)),
                ('icon_name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barman.skillcategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='nemune',
            name='khadamat',
        ),
        migrations.RemoveField(
            model_name='nemune',
            name='subset',
        ),
        migrations.RemoveField(
            model_name='subset',
            name='khadamat',
        ),
        migrations.DeleteModel(
            name='Khadamat',
        ),
        migrations.DeleteModel(
            name='Nemune',
        ),
        migrations.DeleteModel(
            name='Subset',
        ),
    ]
