# Generated by Django 3.2.5 on 2021-07-07 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barman', '0004_auto_20210707_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_subcategories', to='barman.skillcategory'),
        ),
    ]
