# Generated by Django 3.2.5 on 2021-07-26 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_comment_commentofnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentofnews',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_News', to='news.new', verbose_name='عنوان خبر'),
        ),
    ]
