# Generated by Django 3.2.5 on 2021-07-28 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_commentofnews_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentofnews',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_News', to='news.new', verbose_name='عنوان خبر'),
        ),
    ]
