# Generated by Django 3.2.5 on 2021-07-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_auto_20210725_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_uploaded/', verbose_name='تصویر سردسته نمونه کار'),
        ),
    ]
