# Generated by Django 3.2.6 on 2021-08-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='تگ')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='نام خبر')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان خبر')),
                ('image', models.ImageField(upload_to='images/', verbose_name='عکس خبر')),
                ('description', models.TextField(verbose_name='متن خبر')),
                ('category', models.CharField(max_length=100, verbose_name='دسته بندی')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ManyToManyField(to='news.Tag', verbose_name='تگ مربوطه')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'خبر',
            },
        ),
    ]
