# Generated by Django 3.2.5 on 2021-07-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': 'ویدئوها', 'verbose_name_plural': 'ویدئوها'},
        ),
    ]
