# Generated by Django 3.2.5 on 2021-07-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان مقاله')),
                ('text', models.TextField(verbose_name='مقاله')),
                ('image', models.ImageField(upload_to='image_uploaded/', verbose_name='تصویر مقاله')),
            ],
            options={
                'verbose_name': 'مقالات',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
