# Generated by Django 3.2.5 on 2021-07-26 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOfArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('body', models.TextField(verbose_name='متن')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد دیدگاه')),
                ('active', models.BooleanField(default=False, verbose_name='انتشار')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_Article', to='article.article', verbose_name='عنوان خبر')),
            ],
            options={
                'verbose_name': 'نظرات',
                'verbose_name_plural': 'نظرات',
                'ordering': ['created_on'],
            },
        ),
    ]
