# Generated by Django 3.2.5 on 2021-07-26 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_commentofarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentofarticle',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_Article', to='article.article', verbose_name='عنوان مقاله'),
        ),
    ]
