# Generated by Django 3.2.5 on 2021-07-13 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان خدمات')),
                ('description', models.TextField(verbose_name='تومضیحات')),
                ('image', models.ImageField(upload_to='video_uploaded/', verbose_name='تصویر خدمات')),
                ('film', models.FileField(upload_to='video_uploaded/', verbose_name='ویدئو خدمات')),
            ],
            options={
                'verbose_name': 'خدمات',
                'verbose_name_plural': 'خدمات',
            },
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پروژه')),
                ('link', models.CharField(max_length=300, verbose_name='لینک پروژه')),
                ('text', models.TextField(verbose_name='توضیحات پروژه')),
                ('image', models.ImageField(upload_to='image_uploaded', verbose_name='تصویر پروژه')),
                ('film', models.FileField(upload_to='video_uploaded', verbose_name='فیلم پروژه')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.sub', verbose_name='نام سردسته')),
            ],
            options={
                'verbose_name': 'زیرخدمات',
                'verbose_name_plural': 'زیرخدمات',
            },
        ),
    ]
