# Generated by Django 3.2.5 on 2021-07-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='film',
            field=models.FileField(blank=True, upload_to='video_uploaded/', verbose_name='ویدئو خدمات'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='video_uploaded/', verbose_name='تصویر خدمات'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='film',
            field=models.FileField(blank=True, upload_to='video_uploaded', verbose_name='فیلم پروژه'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='image',
            field=models.ImageField(blank=True, upload_to='image_uploaded', verbose_name='تصویر پروژه'),
        ),
    ]
