# Generated by Django 3.2.6 on 2021-08-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نام سوال')),
                ('question', models.CharField(max_length=300, verbose_name='متن سوال')),
                ('answer', models.TextField(verbose_name='پاسخ سوال')),
            ],
            options={
                'verbose_name': 'سوال متدواول',
                'verbose_name_plural': 'سوال متداول',
            },
        ),
    ]
