# Generated by Django 3.2.6 on 2021-08-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام و نام خانوادگی')),
                ('email', models.CharField(max_length=200, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=500, verbose_name='موضوع')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('description', models.TextField(blank=True, null=True, verbose_name='پیغام شما')),
            ],
            options={
                'verbose_name': 'فرم دریافتی',
                'verbose_name_plural': 'فرم دریافتی',
            },
        ),
    ]
