# Generated by Django 3.2.6 on 2021-08-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام عکس')),
                ('picture', models.ImageField(upload_to='images/', verbose_name='عکس')),
            ],
        ),
    ]
