# Generated by Django 3.2.6 on 2021-08-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_main_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main_pic',
            options={'verbose_name': 'عکس اصلی', 'verbose_name_plural': 'عکس اصلی'},
        ),
        migrations.AddField(
            model_name='main_pic',
            name='text',
            field=models.CharField(default='hello word', max_length=300, verbose_name='نوشته عکس'),
            preserve_default=False,
        ),
    ]
