# Generated by Django 3.2.6 on 2021-08-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210808_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام و نام خانوادکی')),
                ('job', models.CharField(max_length=200, verbose_name='شغل')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('picture', models.ImageField(upload_to='images', verbose_name='تصویر کارمند')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمند',
            },
        ),
    ]
